name: "husky_ur5"
joint_model_group_name: "manipulator"
torso_joint_name: "manipulator_lift_joint"
frame_id: "map"
global_link_transform: "gripper_base_link"
tip_to_gripper_offset:
  - 0.15
  - 0.0
  - 0.0
gripper_to_base_rot_offset:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
base_cmd_topic: "cmd_vel" # 原来是/cmd_vel，但是要并行训练改成cmd_vel,后面代码会自动加上命名空间前缀
base_vel_rng: 0.3
base_rot_rng: 1.0
torso_vel_rng: 0.0
z_min: 0.7  #0.39
z_max: 1.15 #1.24
restricted_ws_z_min: 0.4
restricted_ws_z_max: 1.1
# max dist the ee plan is allowed to be from a feasible base plan
# https://docs.hsr.io/hsrb_user_manual_en/overview/basic_specifications.html
arm_range: 0.8
gmm_base_offset: 0.02
kinematics_solver_timeout: 0.01
# values inferred from https://www.brain.kyutech.ac.jp/~hma/robots/hsr/
robot_base_size_meters:
  - 0.99
  - 0.67
inflation_radius_ee: 0.40
initial_joint_values:
  front_left_wheel: 0.022233252144934212
  front_right_wheel: 0.022290179629569806
  gripper_finger1_joint: 0.0005172244939828374
  rear_left_wheel: 0.019372974532483767
  rear_right_wheel: 0.019032215143395703
  ur5_elbow_joint: -0.0007863513851198434
  ur5_shoulder_lift_joint: -1.5705042627235626
  ur5_shoulder_pan_joint: -0.01111974792726489
  ur5_wrist_1_joint: -1.5713908974689739
  ur5_wrist_2_joint: -0.0005968816301642477
  ur5_wrist_3_joint: -0.006540936480208259
gripper_collision_names:
  - 'husky_ur5::gripper_finger1_finger_link::gripper_finger1_finger_link_collision'
  - 'husky_ur5::gripper_finger2_finger_link::gripper_finger2_finger_link_collision'
  - 'husky_ur5::gripper_finger1_finger_tip_link::gripper_finger1_finger_tip_link_collision'
  - 'husky_ur5::gripper_finger2_finger_tip_link::gripper_finger2_finger_tip_link_collision'
  - 'husky_ur5::gripper_finger2_knuckle_link::gripper_finger2_knuckle_link_collision'
  - 'husky_ur5::gripper_finger1_knuckle_link::gripper_finger1_knuckle_link_collision'
  - 'husky_ur5::gripper_finger1_inner_knuckle_link::gripper_finger1_inner_knuckle_link_collision'
  - 'husky_ur5::gripper_finger2_inner_knuckle_link::gripper_finger2_inner_knuckle_link_collision'
